name: Run tests

env:
  OS: ubuntu-latest

on:
  workflow_dispatch
#  schedule:
#    - cron: '44 18 3 8 *'

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: "Download Selenoid"
        run: curl -s https://aerokube.com/cm/bash | bash

      - name: "Start Selenoid"
        run: chmod +x ./cm | ./cm selenoid start --browsers 'chrome' --last-versions 1

      - name: "Give access for workflow to repository"
        uses: actions/checkout@v3

      - name: "Install OpenJDK 17"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: "Run UI tests"
        run: mvn clean test
        continue-on-error: true

      - name: "Generate Allure Report with history"
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          gh_pages: gh-pages
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history

      - name: "Deploy Allure History to the gh-pages branch"
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history